const technicalindicators = require("technicalindicators");

const indexKeys = {
  INSIDE_CANDLE: "INSIDE-CANDLE",
  ABANDONED_BABY: "ABANDONED-BABY",
  BEARISH_ENGULFING: "BEAR-ENGULF",
  BULLISH_ENGULFING: "BULL-ENGULF",
  DARK_CLOUD_COVER: "DARK-CLOUD-COVER",
  DOWNSIDE_TASUKI_GAP: "DOWNSIDE-TASUKI-GAP",
  DOJI: "DOJI",
  DRAGONFLY_DOJI: "DRAGONFLY-DOJI",
  GRAVESTONE_DOJI: "GRAVESTONE-DOJI",
  BEARISH_HARAMI: "BEAR-HARAMI",
  BULLISH_HARAMI: "BULL-HARAMI",
  BEARISH_HARAMI_CROSS: "BEAR-HARAMIX",
  BULLISH_HARAMI_CROSS: "BULL-HARAMIX",
  BULLISH_MARUBOZU: "BULL-MARUBOZU",
  BEARISH_MARUBOZU: "BEAR-MARUBOZU",
  EVENING_DOJI_STAR: "EVENING-DOJI-STAR",
  EVENING_STAR: "EVENINGSTAR",
  PIERCING_LINE: "PIERCING-LINE",
  BULLISH_SPINNING_TOP: "BULL-SPINTOP",
  BEARISH_SPINNING_TOP: "BEAR-SPINTOP",
  MORNING_DOJI_STAR: "MORNING-DOJI-STAR",
  MORNING_STAR: "MORNING-STAR",
  _3BLACK_CROWS: "3BLACK-CROWS",
  _3WHITE_SOLDIERS: "3WHITE-SOLDIERS",
  BULLISH_HAMMER: "BULLHAMMER",
  BEARISH_HAMMER: "BEARHAMMER",
  BULLISH_INVERTED_HAMMER: "BULL-INVERT-HAMMER",
  BEARISH_INVERTED_HAMMER: "BEAR-INVERT-HAMMER",
  HAMMER: "HAMMER",
  HAMMER_UNCONFIRMED: "HAMMER-UNCONF",
  HANGING_MAN: "HANGMAN",
  HANGING_MAN_UNCONFIRMED: "HANGMAN-UNCONF",
  SHOOTING_STAR: "SHOOTSTAR",
  SHOOTING_STAR_UNCONFIRMED: "SHOOTSTAR-UNCONF",
  TWEEZER_TOP: "TWEEZER-TOP",
  TWEEZER_BOTTOM: "TWEEZER-BOTTOM",
  //TECHNICAL INDICATORS
  RSI: "RSI",
  MACD: "MACD",
  SMA: "SMA",
  EMA: "EMA",
  STOCH_RSI: "S-RSI",
  BOLLINGER_BANDS: "BB",
  ADL: "ADL",
  ADX: "ADX",
  ATR: "ATR",
  AWESOME_OSCILLATOR: "AO",
  CCI: "CCI",
  FORCE_INDEX: "FI",
  KST: "KST",
  MFI: "MFI",
  OBV: "OBV",
  PSAR: "PSAR",
  ROC: "ROC",
  STOCH: "STOCH",
  TRIX: "TRIX",
  TYPICAL_PRICE: "TYPICAL",
  VWAP: "VWAP",
  VOLUME_PROFILE: "VP",
  WMA: "WMA",
  WEMA: "WEMA",
  WILLIAMS_R: "WILLIAMS-R",
  ICHIMOKU: "ICHIMOKU",
  //BEHOLDER INDICATORS
  MINI_TICKER: "MINI_TICKER",
  BOOK: "BOOK",
  WALLET: "WALLET",
  LAST_ORDER: "LAST_ORDER",
  LAST_CANDLE: "LAST_CANDLE",
  PREVIOUS_CANDLE: "PREVIOUS_CANDLE",
  TICKER: "TICKER",
};

function RSI(closes, period = 14) {
  const rsiResult = technicalindicators.rsi({
    period: 14,
    values: closes,
  });
  return {
    current: parseFloat(rsiResult[rsiResult.length - 1]),
    previous: parseFloat(rsiResult[rsiResult.length - 2]),
  };
}

function MACD(closes, fastPeriod = 12, slowPeriod = 26, signalPeriod = 9) {
  const macdResult = technicalindicators.macd({
    values: closes,
    SimpleMAOscillator: false,
    SimpleMASignal: false,
    fastPeriod,
    slowPeriod,
    signalPeriod,
  });
  return {
    current: macdResult[macdResult.length - 1],
    previous: macdResult[macdResult.length - 2],
  };
}

module.exports = {
  RSI,
  MACD,
  indexKeys,
};
